name: Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 16.x]
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      PORT: ${{ secrets.PORT }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm run install-server
      - run: npm run test-server

      # Additional steps for CDK deployment
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: CDK Deploy
        run: cdk deploy --all --require-approval never

      - name: Send Deployment Notification
        run: |
          aws ses send-email \
            --region ${{ env.AWS_REGION }} \
            --from ${{ secrets.SENDER_EMAIL }} \
            --destination "ToAddresses=${{ secrets.RECIPIENT_EMAIL }}" \
            --message "Subject={Data=CDK Deployment Notification,Charset=utf-8},Body={Text={Data=CDK stack has been deployed successfully.,Charset=utf-8},Html={Data=<p>CDK stack has been deployed successfully.</p>,Charset=utf-8}}" \
            --profile default
