name: Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: npm run install-server

      - name: Test server
        run: npm run test-server

  deploy:
    name: Deploy CDK Stacks
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cdk dependencies
        run: npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Bootstrap CDK environment
        run: cdk bootstrap

      - name: Deploy CDK stacks
        run: cdk deploy --all --require-approval never

      - name: Send Deployment Notification
        run: |
          aws ses send-email \
            --region ${{ secrets.AWS_REGION }} \
            --from ${{ secrets.SENDER_EMAIL }} \
            --destination "ToAddresses=${{ secrets.RECIPIENT_EMAIL }}" \
            --message "Subject={Data=CDK Deployment Notification,Charset=utf-8},Body={Text={Data=CDK stack has been deployed successfully.,Charset=utf-8},Html={Data=<p>CDK stack has been deployed successfully.</p>,Charset=utf-8}}" \
            --profile default
